symbols:
  - SUN_USDT
  - SLP_USDT
  - FITFI_USDT
  - ICP_USDT
  - JASMY_USDT
  - FTT_USDT
  - XCN_USDT
  - TLM_USDT
  - RACA_USDT
  - MBOX_USDT
  - XCH_USDT
  - BICO_USDT
  - XEM_USDT
  - DHX_USDT
  - BAKE_USDT

